config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show,:index,:edit,:update] do
  	resource :relationships, only: [:create, :destroy]
  	get 'follows' => 'relationships#follower', as: 'follows'
  	get 'followers' => 'relationships#followed', as: 'followers'
  end

  resources :books do
  	resource :favorites, only: [:create, :destroy]
  	resources :book_comments, only: [:create, :destroy]
  end

  root 'home#top'
  get 'home/about' => 'home#about'
  get 'search' => 'search#search'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  attachment :profile_image, destroy: false

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 50}

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得（フォローされている）
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end



def User.search(search,word)
  if search == "forward_match"
    @user = User.where("name LIKE?","#{word}%")
  elsif search == "backward_match"
    @user = User.where("name LIKE?","%#{word}")
  elsif search == "perfect_match"
    @user = User.where("name LIKE?","#{word}")
  elsif search == "partial_match"
    @user = User.where("name LIKE?","%#{word}%")
  else
    @user = User.all
  end
end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render 'edit'
    else
      redirect_to books_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      # users_path→
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

# unless params[:id].to_i == current_user.id
      # redirect_to user_path(current_user)
    # end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<!--users一覧 -->
    <table class="table">
	    <thead>
		    <tr>
			    <th>image</th>
			    <th>name</th>
			    <th colspan="3"></th>
		    </tr>
	    </thead>

	    <tbody>
		    <% users.each do |user| %>
		    <tr>
			    <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			    <td><%= user.name %></td>
			    <td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
			    <td>フォロー数：<%= user.follower.count %></td>
			    <td>フォロワー数：<%= user.followed.count %></td>
			    <td>
			    	<% if current_user != user %>
    					<% if current_user.following?(user) %>
      					<%= link_to 'フォローを外す', user_relationships_path(user.id), method: :delete, class: "btn btn-primary" %>
    					<% else %>
      					<%= link_to 'フォローする', user_relationships_path(user.id),method: :post, class: "btn btn-primary" %>
    					<% end %>
  					<% end %>
			    </td>
		    </tr>
		    <% end %>
	    </tbody>
    </table>
    <!--users一覧 -->

app/views/users/_profile.html.erb
	<table class="table">
	<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>
	<tr>
		<th>follows</th>
		<th><%= link_to user.follower.count, user_follows_path(user) %></th>
	</tr>
	<tr>
		<th>followers</th>
		<th><%= link_to user.followed.count, user_followers_path(user) %></th>
	</tr>
    </table>

  <% if current_user != user %>
    <% if current_user.following?(user) %>
      <%= link_to 'フォローを外す', user_relationships_path(user.id), method: :delete, class: "btn btn-primary" %>
    <% else %>
      <%= link_to 'フォローする', user_relationships_path(user.id),method: :post, class: "btn btn-primary" %>
    <% end %>
  <% end %>


  <% if user == current_user %>
    <div class='row'>
	<%= link_to '', edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
	</div>
  <% end %>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

	<!-- エラーメッセージ表示-->
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3><
			<ul>
				<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<!-- エラーメッセージ表示-->

	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name, class: "name" %>
	</div>

	<div class="field">
		<%= f.label :image %>
		<%= f.attachment_field :profile_image, class: "user_image" %>
	</div>

	<div class="field">
		<%= f.label :introduction %>
		<%= f.text_area :introduction, class: "introduction" %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/users/index.html.erb
<div class="container">
<div class="row">
  <div class="col-xs-3">
  	<div class="row">
    <h2>User info</h2>
    <%= render 'users/profile', user: current_user %>

    <div class="row">
    <h2>New book</h2>
   </div>
    <%= render 'books/newform', book: @book %>

  </div>
  </div>
  <div class="col-xs-9">
    <h2>Users</h2>
    <!--users一覧 -->
    <%= render 'index', users: @users %>
    <!--users一覧 -->
   </div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to user_path(book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book_path(book) %></td>
					<td><%= book.body %></td>
				</tr>
		        <% end %>
		    </tbody>
		</table>
	</div>
</div>
</div>