config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show,:index,:edit,:update] do
  	resource :relationships, only: [:create, :destroy]
  	get 'follows' => 'relationships#follower', as: 'follows'
  	get 'followers' => 'relationships#followed', as: 'followers'
  end

  resources :books do
  	resource :favorites, only: [:create, :destroy]
  	resources :book_comments, only: [:create, :destroy]
  end

  root 'home#top'
  get 'home/about' => 'home#about'
  get 'search' => 'search#search'
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}


	# favorited_by?メソッドを作成
	# このメソッドで、引数で渡されたユーザidがFavoritesテーブル内に存在（exists?）するかどうかを調る
    # 存在していればtrue、存在していなければfalseを返す
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	def self.search(search, word)
        if search == "forward_match"
            @book = Book.where("title LIKE?","#{word}%")
        elsif search == "backward_match"
            @book = Book.where("title LIKE?","%#{word}")
        elsif search == "perfect_match"
            @book = Book.where("title LIKE?","#{word}")
        elsif search == "partial_match"
            @book = Book.where("title LIKE?","%#{word}%")
        else
            @book = Book.all
        end
   end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :baria_user, only: [:edit, :update, :destroy]

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @book_comment = BookComment.new
  end

  def index
    @books = Book.all
    @book =Book.new
  end

  def create
    @book = Book.new(book_params)
    # User must exist 本を投稿する際には誰が投稿したのかという情報を追記する必要があります。
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user = current_user
      render "edit"
    else
    redirect_to books_path
    end
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def baria_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end

end
# unless params[:id].to_i == current_user.id
      # redirect_to user_path(current_user)
    # end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
    <ul class="error">
    	<% if book.errors.any? %>
    	    <li><%= pluralize(book.errors.count, "error") %><span>prohibiited this book from being saved:</span></li>

    		<% book.errors.full_messages.each do |message| %>
    		<li><%= message %></li>
    		<% end %>
    </ul>
        <% end %>



	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %>
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<h1>Editing Book</h1>

		<%= render "books/newform", book: @book %>
		<%= link_to "Show", book_path(@book), class: "book_#{@book.id}" %>
		<%= link_to "Back", books_path, class: "back" %>

	</div>
	<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="container">
	<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to(book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<td>
						<% if book.favorited_by?(current_user) %>
						<li>
  						<%= link_to book_favorites_path(book), method: :delete do %>
    						<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
    						<%= book.favorites.count %> いいね
  						<% end %>
						</li>
						<% else %>
						<li>
  						<%= link_to book_favorites_path(book), method: :post do %>
    						<i class="fa fa-heart-o" aria-hidden="true"></i>
    						<%= book.favorites.count %> いいね
  						<% end %>
						</li>
						<% end %>
					</td>
					<td><%= book.book_comments.count %>件コメント</td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>
</div>

app/views/books/show.html.erb
<div class="container">
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<!-- あってるかな？ -->
		<%= render 'users/profile', user: @book.user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @new_book %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to user_path(@book.user) do %>
							<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, book_path(@book) %></td>
					<td><%= @book.body %></td>

                    <!-- 確認 -->
					<td><% if @book.favorited_by?(current_user) %>
						<li>
  						<%= link_to book_favorites_path(@book), method: :delete do %>
    						<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
    						<%= @book.favorites.count %> いいね
  						<% end %>
						</li>
						<% else %>
						<li>
  						<%= link_to book_favorites_path(@book), method: :post do %>
    						<i class="fa fa-heart-o" aria-hidden="true"></i>
    						<%= @book.favorites.count %> いいね
  						<% end %>
						</li>
						<% end %>
					</td>


					<td><%= @book.book_comments.count %>件コメント</td>
					<% if @book.user == current_user %>
					<td><%= link_to "Edit", edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<% end %>
				</tr>
			</table>

				<p class="mt-5"><strong>Comment</strong></p>
                  <% @book.book_comments.each do |post_comment| %>
                  <table class="table table-striped">
                    <tr>
                      <td class="col-xs-2">
                    <%= attachment_image_tag post_comment.user, :profile_image, :fill, 20, 20, format: 'jpeg', fallback: "no_image.jpg",size:'60x60' %>

                  <div><a href="#" class="link-author"><%= post_comment.user.name %></a></div>
                </td>
                <td class="col-xs-4">
                  <%= post_comment.comment %>
                </td>

                <td class="col-xs-2">
                  <% if post_comment.user == current_user %>
                    <%= link_to "Destroy", book_book_comment_path(post_comment.book, post_comment), method: :delete, class: "btn-sm btn-danger" %>
                  <% end %>
                  </td>
                  </tr>
                  <% end %>
              </table>


			<%= form_for [@book, @book_comment] do |f| %>
			<div class="row">
			<div class="col-sm-12">
				<%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
			</div>
			</div>
			<%= f.submit "送信", class:"btn btn-lg btn-base-1 mt-20 pull-right" %>
			<% end %>

	</div>
</div>
</div>